### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by Drsheppard01** [Portable-Linux-Apps/Portable-Linux-Apps.github.io#1]
I made a big list for apppimage of what is needed to keep the repository up to date. Perhaps this will help you

https://github.com/AppImage/appimage.github.io/issues/3112

**Comment by ivan-hc** [comment]
1. Your list is a great work, many of these names already are available for "AM" and AppMan;
2. Appimage.github.io is only a catalogue of apps that are or were been in Appimage format and many of them are no more available nowhere... please don't tell Probono to remove those (useless) pages, he will never lose his (destructive) delusions of grandeur (the same ones that kill the Appimage package format, see [here](https://www.reddit.com/r/linux/comments/uvzhey/probono_creator_of_appimage_in_an_attempt_to_get/));
3. If you want to share all the apps missing from this list, it is better that they come across the database of "AM" first, in this way we are sure that the apps are real! ;)

**Comment by Drsheppard01** [comment]
> Appimage.github.io is only a catalogue of apps

The problem is that this json file is used for almost all AppImage related projects
> ... he will never lose his (destructive) delusions of grandeur (the same ones that kill the Appimage package format, see [here](https://www.reddit.com/r/linux/comments/uvzhey/probono_creator_of_appimage_in_an_attempt_to_get/));

The best way out is to make your own organization on github, your own infrastructure and promote AppImage or a format based on it (see: [appdwarf](https://github.com/phantop/appdwarf), [shappimage](https://github.com/mgord9518/shappimage)

Here I have also laid out the steps that are required by the appimage: https://social.linux.pizza/@drsheppard/109779906807566912
