### ISSUE TITLE
Please add dark mode

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Portable-Linux-Apps/Portable-Linux-Apps.github.io#16]
With https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by ivan-hc** [comment]
You know? I am already looking for this feature. I don't know how to apply this to github pages.

All pages of the website are Markdowns and settings are at https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/blob/main/_config.yml

**Comment by vitaly-zdanevich** [comment]
Looks like a related documentation https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

**Comment by andy5995** [comment]
I'll try to work on this
