### ISSUE TITLE
Some links should to be relative instead of absolute

### ISSUE THREAD

**Issue by andy5995** [Portable-Linux-Apps/Portable-Linux-Apps.github.io#20]
For testing locally with jekyll, links need to be relative. So if you view the main page, and click on 'audio', it will go to localhost:4000/audio.html when testing, instead of https://portable-linux-apps.github.io/audio.html

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/blob/ea05892de7ce6701f909dd0c4cd54dfa2e34feec/index.md?plain=1#L23C1-L23C81

**Comment by ivan-hc** [comment]
Sorry, I've not understand the issue

**Comment by andy5995** [comment]
Can I show you with screen share on Jitsi? If so, go here https://meet.jit.si/portable-linux-apps-temp
