### ISSUE TITLE
Warning that site.title should be used instead

### ISSUE THREAD

**Issue by andy5995** [Portable-Linux-Apps/Portable-Linux-Apps.github.io#24]
When I test the site with Jekyll, I get the warning:

>GitHub Metadata: site.name is set in _config.yml, but many plugins and themes expect site.title to be used instead. To avoid potential inconsistency, Jekyll GitHub Metadata will not set site.title to the repository's name.

**Comment by ivan-hc** [comment]
the PR has been merged, is the message still appearing?

**Comment by andy5995** [comment]
No, the warning is from https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/blob/074a06ad9553e41afc28584e2c91c198196ca2df/_config.yml#L1

**Comment by ivan-hc** [comment]
try now
