### ISSUE TITLE
Localsend using wrong icon

### ISSUE THREAD

**Issue by GeoBoi254** [Portable-Linux-Apps/Portable-Linux-Apps.github.io#28]
Localsend doesn't use the correct icon as it uses the Flutter icon.

This might be the right icon to use for it.
https://raw.githubusercontent.com/localsend/localsend/refs/heads/main/fastlane/metadata/android/en-US/images/icon.png

**Comment by GeoBoi254** [comment]
I'll try to find other icons that are broken.

**Comment by ivan-hc** [comment]
> I'll try to find other icons that are broken.

thank you so much @GeoBoi254
