### ISSUE TITLE
Typo: ubdate should be update

### ISSUE THREAD

**Issue by rubensa** [Portable-Linux-Apps/Portable-Linux-Apps.github.io#6]
In [README.md](https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/blob/main/README.md?plain=1#L65) `ubdate` should be `update`.

**Comment by ivan-hc** [comment]
Apparently this cold was contagious, I had infected 3 repositories with this copy/paste. Thanks for the tip
